version: "3.8"
services:
  # Contenedor del servidor web con PHP + Apache
  miservidor: 
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports: 
      - 8080:80
    links:
      - basedatos
    # Montamos la web desde el host al directorio web del contenedor
    volumes: 
      - ./html:/var/www/html

  # Contenedor para la base de datos con MySQL
  basedatos:
    image: mysql:5.7
    container_name: bd
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    # Montamos un volumen para MySQL para no perder los datos de bd
    volumes:
      - ./db:/var/lib/mysql

volumes:
  html: {}
  db: {}